# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b48d0bc07e39fbb99d561bafea63f4ce1eee3fe16fb92f91d955bcb66ba8de41f8b96b8eb67cda54c0fa1d6e506520017d61d96aa2c88465ac311061e786a052

test:
  secret_key_base: 6ce4d39727ae65b89ba548ffb24c78eb19b3fa3af29ba94d3af3db3535af8cdbf7d6b94f4defc3ddd745f24372ab9f39c80f5cda021fe51022edb6097cb9bbbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
